version: '3.8'
services:
  database:
    image: mysql:8
    container_name: sgu-database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sgu_db
    ports:
      - "3307:3306"
    volumes:
      - sgu-volume:/var/lib/mysql
    networks:
      - sgu-net
    restart: unless-stopped

  backend:
    image: server:1.0-sgu
    build:
      context: ./server
    environment:
      SERVER_PORT: 8080
      DB_HOST: database
      DB_PORT: 3306
      DB_NAME: sgu_db
      DB_USER: root
      DB_PASS: root
    container_name: sgu-backend
    ports:
      - "8081:8080"
    networks:
      - sgu-net
    depends_on:
      - database

  frontend:
    image: client:1.0-sgu
    build:
      context: ./frontend
      args:
      
        API_HOST: localhost 
        API_PORT: 8081  
        API_BASE: /api
    container_name: sgu-frontend
    ports:
      - "3000:80"
    networks:
      - sgu-net
    depends_on:
      - backend

volumes:
  sgu-volume:
    name: sgu-volume

networks:
  sgu-net:
    external: true
    name: sgu-net